### ISSUE TITLE
Fix stanza bug from #10

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/rdftab.rs#14]
From #10, if we add this XML to `tests/example.owl`:

```xml
   <owl:Restriction>
        <owl:onProperty rdf:resource="http://example.com/develops-from"/>
        <owl:someValuesFrom>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://example.com/part-of"/>
                <owl:someValuesFrom rdf:resource="http://example.com/B"/>
            </owl:Restriction>
        </owl:someValuesFrom>
        <owl:disjointWith>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://example.com/develops-from"/>
                <owl:someValuesFrom>
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://example.com/part-of"/>
                        <owl:someValuesFrom rdf:resource="http://example.com/a"/>
                    </owl:Restriction>
                </owl:someValuesFrom>
            </owl:Restriction>
        </owl:disjointWith>
    </owl:Restriction>
```

and run RDFTab from `master` we get:

stanza|subject|predicate|object|value|datatype|language
---|---|---|---|---|---|---
owl:disjointWith|_:riog00000011|owl:disjointWith|_:riog00000013|||
owl:disjointWith|_:riog00000013|owl:someValuesFrom|_:riog00000014|||
owl:disjointWith|_:riog00000014|owl:someValuesFrom|ex:a|||
owl:disjointWith|_:riog00000014|owl:onProperty|ex:part-of|||
owl:disjointWith|_:riog00000014|rdf:type|owl:Restriction|||
owl:disjointWith|_:riog00000013|owl:onProperty|ex:develops-from|||
owl:disjointWith|_:riog00000013|rdf:type|owl:Restriction|||
owl:disjointWith|_:riog00000011|owl:someValuesFrom|_:riog00000012|||
owl:disjointWith|_:riog00000012|owl:someValuesFrom|ex:B|||
owl:disjointWith|_:riog00000012|owl:onProperty|ex:part-of|||
owl:disjointWith|_:riog00000012|rdf:type|owl:Restriction|||
owl:disjointWith|_:riog00000011|owl:onProperty|ex:develops-from|||
owl:disjointWith|_:riog00000011|rdf:type|owl:Restriction|||

I expect the stanza to be `_:riog00000011` for all these triples. @lmcmicu can you please look into this? I think this is a bug and that it's in code that's shared with your branch.

**Comment by lmcmicu** [comment]
Yes I'll look into it.

**Comment by lmcmicu** [comment]
FYI just confirmed that the bug is indeed present on the `thick-triples` branch as well. I'll attempt to isolate it.
