### ISSUE TITLE
Command not found after following installation instructions

### ISSUE THREAD

**Issue by serenalotreck** [ontodev/rdftab.rs#26]
I am sure it's just a matter of adding something to `$PATH`, but I can't figure out what it is.

I cloned the repo and ran `cargo build` from the root, which ran successfully. However, I still get `-bash: rdftab: command not found` when I try and use it.

I've tried adding `target/debug/rdftab` and `~/rdftab.rs/src/main.rs` to `$PATH`, to no avail.

Help appreciated!

EDIT: I also ran `chmod +x`  for both paths before exporting them to `$PATH`

**Comment by jamesaoverton** [comment]
Ok. If `cargo build` ran successfully then there should be an executable binary at `target/debug/rdftab`. Then run `export PATH="$(pwd)/target/debug:$PATH"` to (1) export the updated `PATH` variable to future commands in the same terminal session, and (2) update the `PATH` to check the `$(pwd)/target/debug` directory for executable files before checking the rest of the `PATH`. (`$(pwd)` expands to the full path of your current directory.)

**Comment by serenalotreck** [comment]
That fixed it, thank you!
