### ISSUE TITLE
alternate schema with different columns for different datatypes

### ISSUE THREAD

**Issue by cmungall** [ontodev/rdftab.rs#8]
Consider a variant of the schema where there are columns for different [sqlite datatypes](https://www.sqlite.org/datatype3.html)

 * integer_value : only populated for relevant xsd types
 * real_value : only populated for relevant xsd types
 * text_value : only populated for relevant xsd types
 * value : always populated, uses TEXT

This would facilitate faster querying and indexing when the client knows the datatype, allows for e.g. ordering of numeric fields

Feel free to close this with minimal comment if this doesn't coherent with the design patterns / philosophy for rdftab.rs

**Comment by cmungall** [comment]
A variant proposal is separate tables for the 3 broad literal types, and a [view](https://www.sqlitetutorial.net/sqlite-create-view/) to present a unified table as is done now

**Comment by jamesaoverton** [comment]
I don't want to do this, but it's good to try and articulate why not:

I'm using this for [Gizmos](https://github.com/ontodev/gizmos), which currently supports extract, export, search, and (HTML) tree. I don't care about numeric support for any of these operations. Do you have a use case where it matters?

This version of RDFTab is focused on SQLite, but we will eventually target Postgres, which has a [much richer type system](https://www.postgresql.org/docs/13/datatype.html). At that point I don't see a clear line to draw between which types get their own columns: Boolean, Date, XML?

The bigger reason is: RDF is good for data integration, but tables are better for most other things. There's lots of good ways to model your data in SQL, including types. From your SQL you can generate an RDFTab view, as you suggest. You can also extract from RDFTab into typed SQL easily enough. But when you're working with RDF, I think literal values should all be strings.

**Comment by cmungall** [comment]
We generally don't have many data properties in our ontologies at the moment. However, this may change, and I believe that to do proper justice to areas like chemistry we will need more numeric values, ranges, and the like in our TBoxes.

And I can see myself using combined TBox + ABox OWL files which are likely to have more individual-level numeric data

But I think your answer is good. Model the data how it's best to model data in SQL, and then have transforms (views, materialized or otherwise) to RDFTab. Let RDFTab do what it's good at and use other structures where necessary. It's been so long since I have done much SQL I forget the nice simplicity of views. No need to force everything into one bucket.
